server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agency
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/data/changelog/db.changelog-master.xml




